version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example123
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example123"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"  # ← Логин для веб-интерфейса
      ME_CONFIG_BASICAUTH_PASSWORD: "securepass"  # ← Пароль для веб-интерфейса
    depends_on:
      - mongodb
    networks:
      - mongodb_network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge